version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mdc-panel-plus
    env_file:
      - stack.env
    ports:
      - "3003:3003"
    restart: unless-stopped